### 엔티티 하나 생성
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "생성 테스트3",
  "description": "생성 테스트3입니다."
}



### 엔티티 하나 삭제
POST http://localhost:8080/users/1/delete
Content-Type: application/json