### 엔티티 하나 생성
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "생성 테스트",
  "description": "생성 테스트입니다."
}



### 엔티티 하나 삭제
POST http://localhost:8080/user/1/delete
Content-Type: application/json